//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reportFavoritomatic
{
    using System;
    using System.Collections.Generic;
    
    public partial class category
    {
        public int category_id { get; set; }
        public Nullable<int> parent_category_id { get; set; }
        public string category_name { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
    }
}
