//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reportFavoritomatic
{
    using System;
    using System.Collections.Generic;
    
    public partial class end_user
    {
        public end_user()
        {
            this.favorites = new HashSet<favorite>();
        }
    
        public string domain_id { get; set; }
        public string user_name { get; set; }
        public Nullable<bool> is_supervisor { get; set; }
        public string supervisor_id { get; set; }
    
        public virtual ICollection<favorite> favorites { get; set; }
    }
}
