//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reportFavoritomatic
{
    using System;
    using System.Collections.Generic;
    
    public partial class favorite
    {
        public int favorite_id { get; set; }
        public string favorite_name { get; set; }
        public string report_id { get; set; }
        public string report_path { get; set; }
        public string user_id { get; set; }
        public string created_by_id { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public Nullable<System.DateTime> next_reminder_date { get; set; }
    
        public virtual end_user end_user { get; set; }
        public virtual report report { get; set; }
    }
}
